name: Deploy DocC to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true  # Auto-enables Pages if not set up
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'  # Matches Swift 6.0.3
      - name: Generate DocC
        uses: fwcd/swift-docc-action@v1
        with:
          target: TestimonialKit
          output: ./docs
          hosting-base-path: TestimonialKit
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'
      - name: Add redirect to index.html
        run: |
          echo "<script>window.location.href += \"/documentation/testimonialkit\"</script>" > docs/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
